site_name: Grafana Async HTTP
site_author: Pranesh Mukhopadhyay
site_description: Async Grafana HTTP API wrapper


theme:
  name: material
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      accent: deep orange
      toggle:
        # icon: material/lightbulb
        icon: material/brightness-4
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: deep orange
      toggle:
        # icon: material/lightbulb-outline
        icon: material/brightness-7
        name: Switch to light mode